name: Require Review Before Merge

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  add-review-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Label PR as needing review
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['awaiting-review-owner']
            });
            
            // Comment on PR to notify that owner review is required
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Review Required ⚠️
              
Thank you for your contribution! 

This PR requires review from @Richajaishwal0 before it can be merged. The PR has been labeled with \`awaiting-review-owner\`.

Please be patient while waiting for the review. If there's any urgency, feel free to mention @Richajaishwal0 in a comment.

Thank you for your understanding.`
            });

  check-review-status:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check if review is required
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = 'Richajaishwal0';
            
            // Get the list of reviews for this PR
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            // Check if the owner has reviewed
            const ownerReviewed = reviews.data.some(review => 
              review.user.login === owner && 
              (review.state === 'APPROVED' || review.state === 'CHANGES_REQUESTED')
            );
            
            if (!ownerReviewed) {
              core.setFailed(`PR requires review from ${owner} before merging`);
            } else {
              console.log(`PR has been reviewed by ${owner}`);
            }
